/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSchedulesIndexRouteImport } from './routes/_authenticated/schedules/index'
import { Route as AuthenticatedBillsIndexRouteImport } from './routes/_authenticated/bills/index'
import { Route as ApiWebhooksClerkRouteImport } from './routes/api/webhooks/clerk'
import { Route as UnauthenticatedSignInSplatRouteImport } from './routes/_unauthenticated/sign-in.$'
import { Route as AuthenticatedSchedulesArchivedRouteImport } from './routes/_authenticated/schedules/archived'
import { Route as AuthenticatedBillsArchivedRouteImport } from './routes/_authenticated/bills/archived'
import { Route as AuthenticatedBillsBillIdRouteImport } from './routes/_authenticated/bills/$billId'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchedulesIndexRoute =
  AuthenticatedSchedulesIndexRouteImport.update({
    id: '/schedules/',
    path: '/schedules/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillsIndexRoute = AuthenticatedBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiWebhooksClerkRoute = ApiWebhooksClerkRouteImport.update({
  id: '/api/webhooks/clerk',
  path: '/api/webhooks/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedSignInSplatRoute =
  UnauthenticatedSignInSplatRouteImport.update({
    id: '/sign-in/$',
    path: '/sign-in/$',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const AuthenticatedSchedulesArchivedRoute =
  AuthenticatedSchedulesArchivedRouteImport.update({
    id: '/schedules/archived',
    path: '/schedules/archived',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillsArchivedRoute =
  AuthenticatedBillsArchivedRouteImport.update({
    id: '/bills/archived',
    path: '/bills/archived',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillsBillIdRoute =
  AuthenticatedBillsBillIdRouteImport.update({
    id: '/bills/$billId',
    path: '/bills/$billId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/bills/archived': typeof AuthenticatedBillsArchivedRoute
  '/schedules/archived': typeof AuthenticatedSchedulesArchivedRoute
  '/sign-in/$': typeof UnauthenticatedSignInSplatRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/bills/': typeof AuthenticatedBillsIndexRoute
  '/schedules/': typeof AuthenticatedSchedulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/bills/archived': typeof AuthenticatedBillsArchivedRoute
  '/schedules/archived': typeof AuthenticatedSchedulesArchivedRoute
  '/sign-in/$': typeof UnauthenticatedSignInSplatRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/bills': typeof AuthenticatedBillsIndexRoute
  '/schedules': typeof AuthenticatedSchedulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/bills/$billId': typeof AuthenticatedBillsBillIdRoute
  '/_authenticated/bills/archived': typeof AuthenticatedBillsArchivedRoute
  '/_authenticated/schedules/archived': typeof AuthenticatedSchedulesArchivedRoute
  '/_unauthenticated/sign-in/$': typeof UnauthenticatedSignInSplatRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/_authenticated/bills/': typeof AuthenticatedBillsIndexRoute
  '/_authenticated/schedules/': typeof AuthenticatedSchedulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/bills/$billId'
    | '/bills/archived'
    | '/schedules/archived'
    | '/sign-in/$'
    | '/api/webhooks/clerk'
    | '/bills/'
    | '/schedules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/bills/$billId'
    | '/bills/archived'
    | '/schedules/archived'
    | '/sign-in/$'
    | '/api/webhooks/clerk'
    | '/bills'
    | '/schedules'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/bills/$billId'
    | '/_authenticated/bills/archived'
    | '/_authenticated/schedules/archived'
    | '/_unauthenticated/sign-in/$'
    | '/api/webhooks/clerk'
    | '/_authenticated/bills/'
    | '/_authenticated/schedules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
  ApiWebhooksClerkRoute: typeof ApiWebhooksClerkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedules/': {
      id: '/_authenticated/schedules/'
      path: '/schedules'
      fullPath: '/schedules/'
      preLoaderRoute: typeof AuthenticatedSchedulesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bills/': {
      id: '/_authenticated/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof AuthenticatedBillsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/webhooks/clerk': {
      id: '/api/webhooks/clerk'
      path: '/api/webhooks/clerk'
      fullPath: '/api/webhooks/clerk'
      preLoaderRoute: typeof ApiWebhooksClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/sign-in/$': {
      id: '/_unauthenticated/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof UnauthenticatedSignInSplatRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/schedules/archived': {
      id: '/_authenticated/schedules/archived'
      path: '/schedules/archived'
      fullPath: '/schedules/archived'
      preLoaderRoute: typeof AuthenticatedSchedulesArchivedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bills/archived': {
      id: '/_authenticated/bills/archived'
      path: '/bills/archived'
      fullPath: '/bills/archived'
      preLoaderRoute: typeof AuthenticatedBillsArchivedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bills/$billId': {
      id: '/_authenticated/bills/$billId'
      path: '/bills/$billId'
      fullPath: '/bills/$billId'
      preLoaderRoute: typeof AuthenticatedBillsBillIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedBillsBillIdRoute: typeof AuthenticatedBillsBillIdRoute
  AuthenticatedBillsArchivedRoute: typeof AuthenticatedBillsArchivedRoute
  AuthenticatedSchedulesArchivedRoute: typeof AuthenticatedSchedulesArchivedRoute
  AuthenticatedBillsIndexRoute: typeof AuthenticatedBillsIndexRoute
  AuthenticatedSchedulesIndexRoute: typeof AuthenticatedSchedulesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedBillsBillIdRoute: AuthenticatedBillsBillIdRoute,
  AuthenticatedBillsArchivedRoute: AuthenticatedBillsArchivedRoute,
  AuthenticatedSchedulesArchivedRoute: AuthenticatedSchedulesArchivedRoute,
  AuthenticatedBillsIndexRoute: AuthenticatedBillsIndexRoute,
  AuthenticatedSchedulesIndexRoute: AuthenticatedSchedulesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UnauthenticatedRouteChildren {
  UnauthenticatedSignInSplatRoute: typeof UnauthenticatedSignInSplatRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedSignInSplatRoute: UnauthenticatedSignInSplatRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
  ApiWebhooksClerkRoute: ApiWebhooksClerkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
